Repository Human-Connection/Nitro-Deployment, pull requests merged in 2019-02, with the labels that each got.

#4 Add db migration worker deployment
  .gitignore
  README.md
  dashboard/admin-user.yaml
  dashboard/role-binding.yaml
  db-migration-worker.yaml
  dummies/backend-service.yaml
  dummies/do-loadbalancer.yaml
  dummies/ingress-backend.yaml
  dummies/nginx.yaml
  dummies/web-service.yaml
  legacy-migration/deployment-backend.yaml
  legacy-migration/deployment-neo4j.yaml
  legacy-migration/volume-claim-mongo-export.yaml
  namespace-staging.json
  namespace-staging.yaml
  secrets.template.yaml
  staging/backend-configmap.yaml
  staging/backend-deployment.yaml
  staging/configmaps.yaml
  staging/deployment-backend.yaml
  staging/deployment-neo4j.yaml
  staging/deployment-web.yaml
  staging/deployment.yaml
  staging/neo4j-configmap.yaml
  staging/neo4j-deployment.yaml
  staging/neo4j-service.yaml
  staging/secrets.yaml.template
  staging/service-backend.yaml
  staging/service-neo4j.yaml
  staging/service-web.yaml
  staging/web-configmap.yaml
Labels: PR: reviewed-approved

#7 Certmanager
  README.md
  db-migration-worker.yaml
  human-connection/configmap.yaml
  human-connection/deployment-backend.yaml
  human-connection/deployment-neo4j.yaml
  human-connection/deployment-web.yaml
  human-connection/https/issuer.yaml
  human-connection/ingress/ingress.yaml
  human-connection/service-backend.yaml
  human-connection/service-neo4j.yaml
  human-connection/service-web.yaml
  legacy-migration/deployment-backend.yaml
  legacy-migration/deployment-neo4j.yaml
  legacy-migration/volume-claim-mongo-export.yaml
  namespace-human-connection.yaml
  namespace-staging.yaml
  secrets.template.yaml
  staging/configmaps.yaml
  staging/service-backend.yaml
  staging/service-web.yaml
Labels: PR: reviewed-approved

#8 Fix Digital Ocean Documentation
  README.md
Labels: PR: reviewed-approved

#10 Fix staging urls
  human-connection/configmap.yaml
Labels: PR: unreviewed, enhancement

#9 Fix wrong secret references
  human-connection/deployment-backend.yaml
  human-connection/deployment-web.yaml
Labels: PR: unreviewed, bug

#11 Improved documentation for remote deployment
  README.md
Labels: PR: unreviewed, documentation
